#!/usr/bin/env bash
#ssh configuration

Host *
    PasswordAuthentification no
    IdentifyFile ~/.ssh/school
    SendEnv LANG LC_*
    HashknownHosts yes
    GSSAPIAuthentification yes
    GSSAPIDelegateCredentials no
